targets=AdditionalFile1.pdf AdditionalFile2.tsv AdditionalFile3.tsv \
		betternorm.pdf betternorm.tex bmcart-biblio.sty bmcart.cls bmc-mathphys.bst references.bib \
		Figure1.pdf Figure2.pdf Figure3.pdf Figure4.pdf Figure5.pdf 
all: $(targets)

$(targets):
	cp ../../manuscript/$@ $@

